swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /devices:
    get:
      operationId: "devices.read"
      tags:
        - "Devices"
      summary: "The devices data structure supported by the server application"
      description: "Read the list of devices"
      responses:
        200:
          description: "Successful read devices list operation"
          schema:
            type: "array"
            items:
              properties:
                bytes_fs:
                  type: "number"
                bytes_ts:
                  type: "number"
                timestamp:
                  type: "number"  
  /devices/{device_uuid}:
    get:
      operationId: "devices.getdevice"
      summary: Gets a device by ID.
      parameters:
        - in: path
          name: device_uuid
          type: string
          required: true
          description: ID of the device to get.
      responses:
        200:
          description: "Successful read devices list operation"
          schema:
            type: "array"
            items:
              properties:
                bytes_fs:
                  type: "number"
                bytes_ts:
                  type: "number"
                timestamp:
                  type: "number"  
    # /devices/{deviceId}:
    # get:
    #   operationId: "devices.getdevice"
    #   summary: Gets a user by ID.
    #   parameters:
    #     - in: path
    #       name: deviceId
    #       required: true
    #       description: Numeric ID of the user to get.
  # /devices/{deviceId}:
  #   get:
  #     tags:
  #       - Users
  #     summary: Gets a user by ID.
  #     description: >
  #       A detailed description of the operation.
  #       Use markdown for rich text representation,
  #       such as **bold**, *italic*, and [links](https://swagger.io).
  #     operationId: devices.getdevice
  #     parameters:
  #       - name: deviceId
  #         in: path
  #         description: Device ID
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Successful operation